version: '3.3'
services:
  db:
    image: mysql
    container_name: ignite-call
    environment:
      MYSQL_DATABASE: 'ignite-call'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'docker'
      MYSQL_ROOT_PASSWORD: 'docker'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data/pg:/data/mysql