version: '3.9'

services:
  db:
    container_name: ignite-call-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ignite-call
    volumes:
      - ./data/pg:/data/postgres